# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(500, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainScreen.sizePolicy().hasHeightForWidth())
        MainScreen.setSizePolicy(sizePolicy)
        MainScreen.setMinimumSize(QtCore.QSize(500, 650))
        MainScreen.setMaximumSize(QtCore.QSize(500, 650))
        self.tabWidget = QtWidgets.QTabWidget(MainScreen)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 480, 630))
        self.tabWidget.setObjectName("tabWidget")
        self.tabOverview = QtWidgets.QWidget()
        self.tabOverview.setAccessibleName("")
        self.tabOverview.setObjectName("tabOverview")
        self.tableOverview = QtWidgets.QTableWidget(self.tabOverview)
        self.tableOverview.setGeometry(QtCore.QRect(10, 10, 450, 580))
        self.tableOverview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableOverview.setAlternatingRowColors(False)
        self.tableOverview.setObjectName("tableOverview")
        self.tableOverview.setColumnCount(2)
        self.tableOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOverview.setHorizontalHeaderItem(1, item)
        self.tableOverview.horizontalHeader().setDefaultSectionSize(224)
        self.tableOverview.horizontalHeader().setSortIndicatorShown(False)
        self.tableOverview.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tabOverview, "")
        self.tabWearables = QtWidgets.QWidget()
        self.tabWearables.setObjectName("tabWearables")
        self.tableWearables = QtWidgets.QTableWidget(self.tabWearables)
        self.tableWearables.setGeometry(QtCore.QRect(10, 10, 450, 550))
        self.tableWearables.setObjectName("tableWearables")
        self.tableWearables.setColumnCount(2)
        self.tableWearables.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWearables.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWearables.setHorizontalHeaderItem(1, item)
        self.tableWearables.horizontalHeader().setDefaultSectionSize(224)
        self.tableWearables.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget = QtWidgets.QWidget(self.tabWearables)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 451, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttonPanelW = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.buttonPanelW.setContentsMargins(0, 0, 0, 0)
        self.buttonPanelW.setObjectName("buttonPanelW")
        self.buttonEditW = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonEditW.setObjectName("buttonEditW")
        self.buttonPanelW.addWidget(self.buttonEditW)
        self.buttonDeleteW = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonDeleteW.setObjectName("buttonDeleteW")
        self.buttonPanelW.addWidget(self.buttonDeleteW)
        self.buttonNewW = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonNewW.setObjectName("buttonNewW")
        self.buttonPanelW.addWidget(self.buttonNewW)
        self.tabWidget.addTab(self.tabWearables, "")
        self.tabConnectedDevices = QtWidgets.QWidget()
        self.tabConnectedDevices.setObjectName("tabConnectedDevices")
        self.layoutWidget1 = QtWidgets.QWidget(self.tabConnectedDevices)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 570, 451, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.buttonPanelCD = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.buttonPanelCD.setContentsMargins(0, 0, 0, 0)
        self.buttonPanelCD.setObjectName("buttonPanelCD")
        self.buttonEditCD = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonEditCD.setObjectName("buttonEditCD")
        self.buttonPanelCD.addWidget(self.buttonEditCD)
        self.buttonDeleteCD = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonDeleteCD.setObjectName("buttonDeleteCD")
        self.buttonPanelCD.addWidget(self.buttonDeleteCD)
        self.buttonNewCD = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonNewCD.setObjectName("buttonNewCD")
        self.buttonPanelCD.addWidget(self.buttonNewCD)
        self.tableConnectedDevices = QtWidgets.QTableWidget(self.tabConnectedDevices)
        self.tableConnectedDevices.setGeometry(QtCore.QRect(10, 10, 450, 550))
        self.tableConnectedDevices.setObjectName("tableConnectedDevices")
        self.tableConnectedDevices.setColumnCount(3)
        self.tableConnectedDevices.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnectedDevices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnectedDevices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnectedDevices.setHorizontalHeaderItem(2, item)
        self.tableConnectedDevices.horizontalHeader().setDefaultSectionSize(149)
        self.tableConnectedDevices.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tabConnectedDevices, "")
        self.tabZones = QtWidgets.QWidget()
        self.tabZones.setObjectName("tabZones")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tabZones)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 570, 451, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.buttonPanelZ = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.buttonPanelZ.setContentsMargins(0, 0, 0, 0)
        self.buttonPanelZ.setObjectName("buttonPanelZ")
        self.buttonEditZ = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonEditZ.setObjectName("buttonEditZ")
        self.buttonPanelZ.addWidget(self.buttonEditZ)
        self.buttonDeleteZ = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonDeleteZ.setObjectName("buttonDeleteZ")
        self.buttonPanelZ.addWidget(self.buttonDeleteZ)
        self.buttonNewZ = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonNewZ.setObjectName("buttonNewZ")
        self.buttonPanelZ.addWidget(self.buttonNewZ)
        self.tableZones = QtWidgets.QTableWidget(self.tabZones)
        self.tableZones.setGeometry(QtCore.QRect(10, 10, 450, 550))
        self.tableZones.setObjectName("tableZones")
        self.tableZones.setColumnCount(2)
        self.tableZones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(1, item)
        self.tableZones.horizontalHeader().setDefaultSectionSize(224)
        self.tableZones.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tabZones, "")
        self.tabProfiles = QtWidgets.QWidget()
        self.tabProfiles.setObjectName("tabProfiles")
        self.tableProfiles = QtWidgets.QTableWidget(self.tabProfiles)
        self.tableProfiles.setGeometry(QtCore.QRect(10, 10, 450, 550))
        self.tableProfiles.setObjectName("tableProfiles")
        self.tableProfiles.setColumnCount(2)
        self.tableProfiles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProfiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProfiles.setHorizontalHeaderItem(1, item)
        self.tableProfiles.horizontalHeader().setDefaultSectionSize(224)
        self.tableProfiles.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget2 = QtWidgets.QWidget(self.tabProfiles)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 570, 451, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.buttonPanelP = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.buttonPanelP.setContentsMargins(0, 0, 0, 0)
        self.buttonPanelP.setObjectName("buttonPanelP")
        self.buttonEditP = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonEditP.setObjectName("buttonEditP")
        self.buttonPanelP.addWidget(self.buttonEditP)
        self.buttonDeleteP = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonDeleteP.setObjectName("buttonDeleteP")
        self.buttonPanelP.addWidget(self.buttonDeleteP)
        self.buttonActivateP = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonActivateP.setObjectName("buttonActivateP")
        self.buttonPanelP.addWidget(self.buttonActivateP)
        self.buttonNewP = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonNewP.setObjectName("buttonNewP")
        self.buttonPanelP.addWidget(self.buttonNewP)
        self.tabWidget.addTab(self.tabProfiles, "")

        self.retranslateUi(MainScreen)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "D.R.E.W. System Tool"))
        item = self.tableOverview.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Zone Name"))
        item = self.tableOverview.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Wearables Present"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverview), _translate("MainScreen", "Overview"))
        item = self.tableWearables.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Name"))
        item = self.tableWearables.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Hardware ID"))
        self.buttonEditW.setText(_translate("MainScreen", "Edit"))
        self.buttonDeleteW.setText(_translate("MainScreen", "Delete"))
        self.buttonNewW.setText(_translate("MainScreen", "New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWearables), _translate("MainScreen", "Wearables"))
        self.buttonEditCD.setText(_translate("MainScreen", "Edit"))
        self.buttonDeleteCD.setText(_translate("MainScreen", "Delete"))
        self.buttonNewCD.setText(_translate("MainScreen", "New"))
        item = self.tableConnectedDevices.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Name"))
        item = self.tableConnectedDevices.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Type"))
        item = self.tableConnectedDevices.horizontalHeaderItem(2)
        item.setText(_translate("MainScreen", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConnectedDevices), _translate("MainScreen", "Connected Devices"))
        self.buttonEditZ.setText(_translate("MainScreen", "Edit"))
        self.buttonDeleteZ.setText(_translate("MainScreen", "Delete"))
        self.buttonNewZ.setText(_translate("MainScreen", "New"))
        item = self.tableZones.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Name"))
        item = self.tableZones.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Module Hardware ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabZones), _translate("MainScreen", "Zones"))
        item = self.tableProfiles.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Name"))
        item = self.tableProfiles.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Active"))
        self.buttonEditP.setText(_translate("MainScreen", "Edit"))
        self.buttonDeleteP.setText(_translate("MainScreen", "Delete"))
        self.buttonActivateP.setText(_translate("MainScreen", "Activate"))
        self.buttonNewP.setText(_translate("MainScreen", "New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProfiles), _translate("MainScreen", "Profiles"))

