# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profiledialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProfileDialog(object):
    def setupUi(self, ProfileDialog):
        ProfileDialog.setObjectName("ProfileDialog")
        ProfileDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProfileDialog.resize(420, 660)
        self.labelName = QtWidgets.QLabel(ProfileDialog)
        self.labelName.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.labelName.setObjectName("labelName")
        self.inputName = QtWidgets.QPlainTextEdit(ProfileDialog)
        self.inputName.setGeometry(QtCore.QRect(90, 20, 311, 21))
        self.inputName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inputName.setObjectName("inputName")
        self.labelZones = QtWidgets.QLabel(ProfileDialog)
        self.labelZones.setGeometry(QtCore.QRect(20, 260, 101, 16))
        self.labelZones.setObjectName("labelZones")
        self.labelDevices = QtWidgets.QLabel(ProfileDialog)
        self.labelDevices.setGeometry(QtCore.QRect(40, 360, 191, 16))
        self.labelDevices.setObjectName("labelDevices")
        self.labelThreshold = QtWidgets.QLabel(ProfileDialog)
        self.labelThreshold.setGeometry(QtCore.QRect(40, 300, 191, 16))
        self.labelThreshold.setObjectName("labelThreshold")
        self.sliderThreshold = QtWidgets.QSlider(ProfileDialog)
        self.sliderThreshold.setGeometry(QtCore.QRect(40, 320, 271, 22))
        self.sliderThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.sliderThreshold.setObjectName("sliderThreshold")
        self.spinnerThreshold = QtWidgets.QDoubleSpinBox(ProfileDialog)
        self.spinnerThreshold.setGeometry(QtCore.QRect(320, 320, 61, 22))
        self.spinnerThreshold.setObjectName("spinnerThreshold")
        self.tableDevices = QtWidgets.QTableWidget(ProfileDialog)
        self.tableDevices.setGeometry(QtCore.QRect(40, 440, 340, 130))
        self.tableDevices.setObjectName("tableDevices")
        self.tableDevices.setColumnCount(3)
        self.tableDevices.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDevices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDevices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDevices.setHorizontalHeaderItem(2, item)
        self.tableDevices.horizontalHeader().setDefaultSectionSize(113)
        self.tableDevices.horizontalHeader().setStretchLastSection(True)
        self.dropdownDevice = QtWidgets.QComboBox(ProfileDialog)
        self.dropdownDevice.setGeometry(QtCore.QRect(40, 380, 341, 22))
        self.dropdownDevice.setObjectName("dropdownDevice")
        self.dropdownZone = QtWidgets.QComboBox(ProfileDialog)
        self.dropdownZone.setGeometry(QtCore.QRect(120, 260, 281, 22))
        self.dropdownZone.setObjectName("dropdownZone")
        self.buttonAddDevice = QtWidgets.QPushButton(ProfileDialog)
        self.buttonAddDevice.setGeometry(QtCore.QRect(280, 410, 101, 23))
        self.buttonAddDevice.setObjectName("buttonAddDevice")
        self.buttonRemoveDevice = QtWidgets.QPushButton(ProfileDialog)
        self.buttonRemoveDevice.setGeometry(QtCore.QRect(280, 580, 101, 23))
        self.buttonRemoveDevice.setObjectName("buttonRemoveDevice")
        self.labelWearables = QtWidgets.QLabel(ProfileDialog)
        self.labelWearables.setGeometry(QtCore.QRect(20, 60, 161, 16))
        self.labelWearables.setObjectName("labelWearables")
        self.tableWearables = QtWidgets.QTableWidget(ProfileDialog)
        self.tableWearables.setGeometry(QtCore.QRect(40, 80, 340, 130))
        self.tableWearables.setObjectName("tableWearables")
        self.tableWearables.setColumnCount(2)
        self.tableWearables.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWearables.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWearables.setHorizontalHeaderItem(1, item)
        self.tableWearables.horizontalHeader().setDefaultSectionSize(169)
        self.tableWearables.horizontalHeader().setStretchLastSection(True)
        self.buttonInclude = QtWidgets.QPushButton(ProfileDialog)
        self.buttonInclude.setGeometry(QtCore.QRect(330, 220, 51, 23))
        self.buttonInclude.setObjectName("buttonInclude")
        self.buttonIgnore = QtWidgets.QPushButton(ProfileDialog)
        self.buttonIgnore.setGeometry(QtCore.QRect(270, 220, 51, 23))
        self.buttonIgnore.setObjectName("buttonIgnore")
        self.widget = QtWidgets.QWidget(ProfileDialog)
        self.widget.setGeometry(QtCore.QRect(250, 620, 158, 25))
        self.widget.setObjectName("widget")
        self.buttonPanel = QtWidgets.QHBoxLayout(self.widget)
        self.buttonPanel.setContentsMargins(0, 0, 0, 0)
        self.buttonPanel.setObjectName("buttonPanel")
        self.buttonCancel = QtWidgets.QPushButton(self.widget)
        self.buttonCancel.setObjectName("buttonCancel")
        self.buttonPanel.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(self.widget)
        self.buttonSave.setObjectName("buttonSave")
        self.buttonPanel.addWidget(self.buttonSave)

        self.retranslateUi(ProfileDialog)
        QtCore.QMetaObject.connectSlotsByName(ProfileDialog)

    def retranslateUi(self, ProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        ProfileDialog.setWindowTitle(_translate("ProfileDialog", "Profile Setup"))
        self.labelName.setText(_translate("ProfileDialog", "Profile Name:"))
        self.labelZones.setText(_translate("ProfileDialog", "Properties for Zone:"))
        self.labelDevices.setText(_translate("ProfileDialog", "Connected Devices:"))
        self.labelThreshold.setText(_translate("ProfileDialog", "Zone Threshold (device to wearable):"))
        item = self.tableDevices.horizontalHeaderItem(0)
        item.setText(_translate("ProfileDialog", "Device"))
        item = self.tableDevices.horizontalHeaderItem(1)
        item.setText(_translate("ProfileDialog", "Zone Entry Action"))
        item = self.tableDevices.horizontalHeaderItem(2)
        item.setText(_translate("ProfileDialog", "Zone Exit Action"))
        self.buttonAddDevice.setText(_translate("ProfileDialog", "Add to Zone"))
        self.buttonRemoveDevice.setText(_translate("ProfileDialog", "Remove from Zone"))
        self.labelWearables.setText(_translate("ProfileDialog", "Choose Wearable Units:"))
        item = self.tableWearables.horizontalHeaderItem(0)
        item.setText(_translate("ProfileDialog", "Wearable"))
        item = self.tableWearables.horizontalHeaderItem(1)
        item.setText(_translate("ProfileDialog", "Included"))
        self.buttonInclude.setText(_translate("ProfileDialog", "Include"))
        self.buttonIgnore.setText(_translate("ProfileDialog", "Ignore"))
        self.buttonCancel.setText(_translate("ProfileDialog", "Cancel"))
        self.buttonSave.setText(_translate("ProfileDialog", "Save"))

